esphome:
  name: garage-door-opener
  friendly_name: Garage Door Opener

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "$api_password"

ota:
  - platform: esphome
    password: "$password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: gpio
    pin: GPIO26
    id: gpio26_output

button:
  - platform: template
    name: Garage Door Button
    on_press:
      - output.turn_on: gpio26_output
      - delay: 200ms
      - output.turn_off: gpio26_output
     